export type Package =
  | '@angular-eslint/schematics'
  | '@biomejs/biome'
  | '@commitlint/cli'
  | '@commitlint/config-conventional'
  | 'eslint'
  | 'eslint-plugin-prettier'
  | 'eslint-plugin-simple-import-sort'
  | 'eslint-plugin-unicorn'
  | 'eslint-plugin-unused-imports'
  | 'husky'
  | 'lint-staged'
  | 'prettier'
  | 'prettier-plugin-organize-attributes'
  | 'stylelint'
  | 'stylelint-config-standard-scss';
